openapi: 3.0.0
info:
  title: Caregiving API
  version: 0.1.0
  description: |
    A minimal API description for the caregiving application. These endpoints are suggestions
    and can be extended as the app grows. They map closely to the database tables defined in
    schema.sql.
paths:
  /api/clients:
    get:
      summary: List clients
      responses:
        '200':
          description: A JSON array of clients
    post:
      summary: Create a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: Client created
  /api/clients/{id}:
    get:
      summary: Get a client by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Client ID
      responses:
        '200':
          description: A client object
        '404':
          description: Client not found
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        dob:
          type: string
          format: date
        primary_language:
          type: string
        mobility_level:
          type: string
        risk_level:
          type: string
